services:
  backend:
    image: vanshjangir/rapid-go:backend
    build:
      context: ./server/
      dockerfile: Backend.Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  websocket:
    image: vanshjangir/rapid-go:websocket
    build:
      context: ./server/
      dockerfile: Websocket.Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  client:
    image: vanshjangir/rapid-go:client
    build:
      context: ./frontend/
    env_file:
        - ./frontend/.env
    ports:
      - "5173:80"

  redis:
    image: vanshjangir/rapid-go:redis
    ports:
      - "6379:6379"
