services:
  server:
    image: rg_server
    build:
      context: ./server/
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - POSTGRES_HOST=host.docker.internal
    env_file:
      - ./server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  client:
    image: rg_client
    build:
      context: ./webclient/
      args:
        - ENV_FILE=.env
    ports:
      - "5173:80"
