services:
  backend:
    image: rg_backend
    build:
      context: ./server/cmd/backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - POSTGRES_HOST=host.docker.internal
    env_file:
      - ./server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  websocket:
    image: rg_websocket
    build:
      context: ./server/cmd/websocket
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=release
      - POSTGRES_HOST=host.docker.internal
    env_file:
      - ./server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  client:
    image: rg_client
    build:
      context: ./frontend/
      args:
        - ENV_FILE=.env.production
    ports:
      - "5173:80"
